project:
  name: Ozon Code Platform Template API
  debug: true
  environment: development

grpc:
  host: 0.0.0.0
  port: 8082
  maxConnectionIdle: 5 # Minutes
  timeout: 15 # Seconds
  maxConnectionAge: 5 # Minutes

retranslator:
  chanSize: 512
  consumerCount: 100
  consumeTimeout: 1 # Seconds
  consumeBatchSize: 10
  producerCount: 20
  workerCount: 10

rest:
  host: 0.0.0.0
  port: 8080

metrics:
  host: 0.0.0.0
  port: 9100
  path: /metrics

jaeger:
  service: "com-request-api"
  host: "localhost"
  port: ":5778"

status:
  host: 0.0.0.0
  port: 8000
  livenessPath: /live
  readinessPath: /ready
  versionPath: /version

database:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  name: ozonmp
  sslmode: disable
  migrations: migrations
  driver: pgx
  retry: 10

redis:
  addrs:
    - redis:6379

kafka:
  capacity: 1024
  topic: "com-request-events"
  groupId: "com-request-api"
  brokers:
    - "kafka-1:9092"
    - "kafka-2:9092"
    - "kafka-3:9092"
    - "localhost:9094"
    - "localhost:9095"
    - "localhost:9096"

graylog:
  proto: udp
  host: graylog
  port: 12201
